INSERT INTO [dbo].[File_Config] (
    [id], [childPath], [file_name], [file_type], [format], [spName], [spParam], [spParamValue], [dirName], [segment], [folderName], [created_at], [reserved], [notifyMe]
) VALUES
(2, '', 'BhavCopy_NSE_CM_0_0_0_#_F_0000.csv.zip', 'T', 'YYYY-MM-DD', 'UDIFF_CMBhavcopy', 'Module-ExchangeSegmentID', 'InsUpdate_Trans_DailyStatistics-1', 'common', 'CM', 'bhavcopy', '', '', '377'),
(3, '', 'CM_MTM_Prices_#.csv', 'N', 'DD-MM-YYYY', 'Import_NSECL_Price', 'Module-EXCHNAGESEGMENT', 'InsUpdate-1', 'common', 'CM', 'clearing', '', '', ''),
(4, '', 'C_SEC_#_NSE.csv', 'N', 'DD-MM-YYYY', 'Import_N698_Scrips', 'Module-ModifyUser', 'nSEsCRIPS-9999', 'common', 'CM', 'clearing', '', '', ''),
(5, '', 'NCL_APPLICABLE_SYMBOL_#.csv', 'N', 'DD-MM-YYYY', 'Update_NCL_Scrips', 'Module-ModifyUser', 'NCL_Scrips-9999', 'common', 'CM', 'clearing', '', '', ''),
(6, '', 'BSE_Scrip_Series_Mapping_#.csv', 'N', 'DD-MM-YYYY', 'Update_NSECL_ScripCodes', 'Module-ModifyUser', 'NSECLCodes-9999', 'common', 'CM', 'clearing', '', '', ''),
(7, '', 'SettlementMaster_NCL_CM_0_0_0_#00_0_0000.csv.gz', 'N', 'YYYY-MM', 'NSESettCalender_CSV23', '-', '-', 'common', 'CM', 'clearing', '', '', ''),
(8, '', 'C_VAR1_#_6.DAT', 'N', 'DD-MM-YYYY', 'SP_INSUP_Trans_DailyVar', 'Module-ModifyUser-FileDate-ExcSegmt', 'DailyVar-9999-2024|12|28-1', 'common', 'CM', 'varrate', '', '', ''),
(9, '', 'F_*_SEC_PLEDGE_#_01.csv.gz', 'E', 'DD-MM-YYYY', 'Reco_NCLPledgeSecurities', 'CreateUser', '9999', 'member', 'FO', 'Reports', '', '', ''),
(10, '', 'F_*_SEC_PLEDGE_#_02.csv.gz', 'E', 'DD-MM-YYYY', 'Reco_NCLPledgeSecurities', 'CreateUser', '9999', 'member', 'FO', 'Reports', '', '', ''),
(11, 'Standard report', 'Margin_NCL_FO_0_CM_*_#_P_1100.csv.gz', 'N', 'YYYY-MM-DD', 'UDIFF_NSEFO_Margin', 'Module-ModifyUser-ExcSegmt-ExchangeTrades_CompanyID', 'Import-9999-${FO}-COR0000002', 'member', 'FO', 'Reports', '', '', ''),
(12, 'Standard report', 'Margin_NCL_FO_0_CM_*_#_P_1230.csv.gz', 'N', 'YYYY-MM-DD', 'UDIFF_NSEFO_Margin', 'Module-ModifyUser-ExcSegmt-ExchangeTrades_CompanyID', 'Import-9999-${FO}-COR0000002', 'member', 'FO', 'Reports', '', '', ''),
(13, 'Standard report', 'Margin_NCL_FO_0_CM_*_#_P_1430.csv.gz', 'N', 'YYYY-MM-DD', 'UDIFF_NSEFO_Margin', 'Module-ModifyUser-ExcSegmt-ExchangeTrades_CompanyID', 'Import-9999-${FO}-COR0000002', 'member', 'FO', 'Reports', '', '', '77'),
(14, 'Standard report', 'Margin_NCL_FO_0_CM_*_#_P_1530.csv.gz', 'N', 'YYYY-MM-DD', 'UDIFF_NSEFO_Margin', 'Module-ModifyUser-ExcSegmt-ExchangeTrades_CompanyID', 'Import-9999-${FO}-COR0000002', 'member', 'FO', 'Reports', '', '', '77'),
(15, 'Standard report', 'Margin_NCL_FO_0_CM_*_#_F_0000.csv.gz', 'N', 'YYYY-MM-DD', 'UDIFF_NSEFO_Margin', 'Module-ModifyUser-ExcSegmt-ExchangeTrades_CompanyID', 'Import-9999-${FO}-COR0000002', 'member', 'FO', 'Reports', '', '', '77'),
(16, '', 'C_SA04_*_#.lis.gz', 'N', 'DD-MM-YYYY', 'Import_NSE_SA04', 'COMPANY_ID-SegmentID-ModifyUser', 'COR0000002-${CM}-9999', 'member', 'CM', 'Reports', '', '', ''),
(17, '', 'DeliveryDpo_NCL_CM_EquityT1_CM_*_#_F_0000.csv.gz', 'Y', 'YYYY-MM-DD', 'UDIFF_NSE_DeliveryDpo', 'file_path-file_name-compid-segid-FinYear-userid', 'file_path- -COR0000002-${CM}-2025|2026-9999', 'member', 'CM', 'Reports', '', '', ''),
(18, '', 'DeliveryDpo_NCL_CM_EquityT1_CM_*_#_P_0002.csv.gz', 'Y', 'YYYY-MM-DD', 'UDIFF_NSE_DeliveryDpo', 'file_path-file_name-compid-segid-FinYear-userid', 'file_path- -COR0000002-${CM}-2025|2026-9999', 'member', 'CM', 'Reports', '', '', ''),
(19, '', 'C_*_SEC_PLEDGE_#_01.csv.gz', 'E', 'DD-MM-YYYY', 'Reco_NCLPledgeSecurities', 'CreateUser', '9999', 'member', 'CM', 'Reports', '', '', ''),
(20, '', 'C_*_SEC_PLEDGE_#_02.csv.gz', 'E', 'DD-MM-YYYY', 'Reco_NCLPledgeSecurities', 'CreateUser', '9999', 'member', 'CM', 'Reports', '', '', ''),
(21, '', 'STT_NCL_CM_0_CM_*_#_F_0000.csv.gz', 'N', 'YYYY-MM-DD', 'Import_NSECM_MWST', 'COMPANY_ID-SegmentID-ModifyUser', 'COR0000002-${CM}-9999', 'member', 'CM', 'Reports', '', '', ''),
(22, '', 'C_MG13_*_#.lis.gz', 'N', 'DD-MM-YYYY', 'Import_NSECM_MG13', 'COMPANY_ID-SegmentID-ModifyUser', 'COR0000002-${CM}-9999', 'member', 'CM', 'Reports', '', '', ''),
(23, '', 'C_MG01_*_#.lis', 'N', 'DD-MM-YYYY', 'Import_NSCCL_MarginReport', 'COMPANY_ID-SegmentId-ModifyUser', 'COR0000002-${CM}-9999', 'member', 'CM', 'Reports', '', '', ''),
(24, '', 'COLLDTLS_*_#_01.CSV.gz', 'N', 'YYYY-MM-DD', 'Import_NSCCL_MemberCapital', 'COMPANY_ID-SegmentId-ModifyUser', 'COR0000002-${CM}-9999', 'member', 'CM', 'Reports', '', '', ''),
(25, '', 'C_CC02_*_#.csv.gz', 'N', 'DD-MM-YYYY', 'Import_NSE_CC02', 'COMPANY_ID-SegmentID-ModifyUser', 'COR0000002-${CM}-9999', 'member', 'CM', 'Reports', '', '', ''),
(26, '', 'StampDuty_NCL_CM_0_CM_*_#_F_0000.csv.gz', 'N', 'YYYY-MM-DD', 'Import_NSECM_SD0n', 'COMPANY_ID-SegmentID-ModifyUser', 'COR0000002-${CM}-9999', 'member', 'CM', 'Reports', '', '', ''),
(27, 'Standard report', 'Margin_NCL_CM_0_CM_*_#_P_1100.csv.gz', 'N', 'YYYY-MM-DD', 'UDIFF_NSECM_MarginP', 'COMPANY_ID-SegmentID-ModifyUser', 'COR0000002-${CM}-9999', 'member', 'CM', 'Reports', '', '', ''),
(28, 'Standard report', 'Margin_NCL_CM_0_CM_*_#_P_1230.csv.gz', 'N', 'YYYY-MM-DD', 'UDIFF_NSECM_MarginP', 'COMPANY_ID-SegmentID-ModifyUser', 'COR0000002-${CM}-9999', 'member', 'CM', 'Reports', '', '', ''),
(29, 'Standard report', 'Margin_NCL_CM_0_CM_*_#_P_1430.csv.gz', 'N', 'YYYY-MM-DD', 'UDIFF_NSECM_MarginP', 'COMPANY_ID-SegmentID-ModifyUser', 'COR0000002-${CM}-9999', 'member', 'CM', 'Reports', '', '', ''),
(30, 'Standard report', 'Margin_NCL_CM_0_CM_*_#_P_1530.csv.gz', 'N', 'YYYY-MM-DD', 'UDIFF_NSECM_MarginP', 'COMPANY_ID-SegmentID-ModifyUser', 'COR0000002-${CM}-9999', 'member', 'CM', 'Reports', '', '', ''),
(31, 'Standard report', 'Margin_NCL_CM_0_CM_*_#_P_0000.csv.gz', 'N', 'YYYY-MM-DD', 'UDIFF_NSECM_MarginP', 'COMPANY_ID-SegmentID-ModifyUser', 'COR0000002-${CM}-9999', 'member', 'CM', 'Reports', '', '', ''),
(32, 'Standard report', 'Margin_NCL_CM_0_CM_*_#_F_0000.csv.gz', 'N', 'YYYY-MM-DD', 'UDIFF_NSECM_Margin', 'COMPANY_ID-SegmentID-ModifyUser', 'COR0000002-${CM}-9999', 'member', 'CM', 'Reports', '', '', ''),
(33, 'Dnld', '*_CEP#.D^', 'I-1', 'YYYY-MM-DD', 'Import_NSECM_EPI_CEP', 'COMPANY_ID-SegmentID-ModifyUser', 'COR0000002-${CM}-9999', 'member', 'CM', 'CEP', '', '', ''),
(34, '', 'CM_ORD_LOG_#_*.CSV.gz', 'N', 'DD-MM-YYYY', 'Import_NSECM_Orders', 'SegmentId-COMPANY_ID-ModifyUser', '${CM}-COR0000002-9999', 'member', 'CM', 'Onlinebackup', '', '', ''),
(35, '', 'Trade_NSE_CM_0_TM_*_#_F_0000.csv.gz', 'N', 'YYYY-MM-DD', 'UDIFF_NSECM_Trades', 'ModifyUser-ExcSegmt-ExchangeTrades_CompanyID-LckTradeDate-ExpireDate-LockMsg', '9999-${CM}-COR0000002-2025|12|01-2048|12|01-lic Expired', 'member', 'CM', 'Onlinebackup', '', '', ''),
(36, '', 'F_CN01_NSE_#.CSV.gz', 'N', 'DD-MM-YYYY', 'InsertFODataForSelectLOT', 'Module-ModifyUser-ExchangeSegmentID', '-9999-2', 'common', 'FO', 'MarketReports', '', '', ''),
(37, '', 'Trade_NSE_FO_0_TM_*_#_F_0000.csv.gz', 'N', 'YYYY-MM-DD', 'UDIFF_NSEFO_Trades', 'ModifyUser-ExcSegmt-ExchangeTrades_CompanyID-LckTradeDate-ExpireDate-LockMsg', '9999-${FO}-COR0000002-2025|01|01-2048|12|01-lic Expired', 'member', 'FO', 'Onlinebackup', '', '', ''),
(38, '', 'STT_NCL_FO_0_CM_*_#_F_0000.csv.gz', 'N', 'YYYY-MM-DD', 'UDIFF_NSEFO_STT', 'COMPANY_ID-SegmentID-ModifyUser', 'COR0000002-${FO}-9999', 'member', 'FO', 'Reports', '', '', ''),
(39, '', 'StampDuty_NCL_FO_0_CM_*_#_F_0000.csv.gz', 'N', 'YYYY-MM-DD', 'UDIFF_NSEFO_StampDuty', 'COMPANY_ID-SegmentID-ModifyUser', 'COR0000002-${FO}-9999', 'member', 'FO', 'Reports', '', '', ''),
(40, '', 'Position_NCL_FO_0_CM_*_#_F_0000.csv.gz', 'E', 'YYYY-MM-DD', 'UDIFF_NSEFO_Position', 'ModifyUser-ExcSegmt-ExchangeTrades_CompanyID-LckTradeDate-ExpireDate-LockMsg', '9999-${FO}-COR0000002-2025|12|01-2048|12|01-lic Expired', 'member', 'FO', 'Reports', '', '', ''),
(41, '', 'C_*_DFNS_#.csv.gz', 'E/Z', 'DD-MM-YYYY', 'SP_INSUP_FUNDFILES', 'Module-ModifyUser-ExcSegmt-ExchangeSegmentID-CashBankAccount-FileName-ExchangeTrades_CompanyID-FinYear', 'InsertTradeData-9999-${CM}-1-ICBCMST-DFNS-COR0000002-2025|2026', 'member', 'CM', 'Reports', '1900-01-01 00:00:00.000', 'xmlCashBankInsert/cashBankData-createuser-finyear-compID-CashBankName-TDate-BRS/-9999-2025|2026-COR0000002-ICBCMST-#-0', ''),
(42, '', 'F_AEL_OPT_CONTRACTS_#.csv.gz', 'N', 'DD-MM-YYYY', '-', '-', '-', 'common', 'FO', 'Limit Files', '', '', ''),
(43, '', 'ael_#.csv', 'N', 'DD-MM-YYYY', '-', '-', '-', 'common', 'FO', 'Limit Files', '', '', ''),
(44, '', 'nsccl.#.i01.spn.gz', 'N', 'YYYY-MM-DD', '-', '-', '-', 'common', 'FO', 'Parameter', '', '', ''),
(45, '', 'nsccl.#.i02.spn.gz', 'N', 'YYYY-MM-DD', '-', '-', '-', 'common', 'FO', 'Parameter', '', '', ''),
(46, '', 'nsccl.#.i03.spn.gz', 'N', 'YYYY-MM-DD', '-', '-', '-', 'common', 'FO', 'Parameter', '', '', ''),
(47, '', 'nsccl.#.i04.spn.gz', 'N', 'YYYY-MM-DD', '-', '-', '-', 'common', 'FO', 'Parameter', '', '', ''),
(48, '', 'nsccl.#.i05.spn.gz', 'N', 'YYYY-MM-DD', '-', '-', '-', 'common', 'FO', 'Parameter', '', '', ''),
(49, '', 'F_MG13_*_#.lis.gz', 'N', 'DD-MM-YYYY', 'SP_INSUP_MarginFOCSV_New2', 'Module-ModifyUser-ExcSegmt-Date-ExchangeTrades_CompanyID', 'InsertMarginFODataCSV-9999-${FO}--COR0000002', 'member', 'FO', 'Reports', '', '', '');